CREATE TABLE IF NOT EXISTS GENDERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS JOBS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    SALARY DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS EMPLOYEES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    GENDER_ID INT NOT NULL,
    JOB_ID INT NOT NULL,
    NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    BIRTHDATE DATE,
    FOREIGN KEY (GENDER_ID) REFERENCES GENDERS(ID),
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(ID)
);

CREATE TABLE IF NOT EXISTS EMPLOYEE_WORKED_HOURS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    EMPLOYEE_ID INT NOT NULL,
    WORKED_HOURS INT,
    WORKED_DATE DATE,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(ID)
);

-- Inserts para GENDERS
INSERT INTO GENDERS (NAME) VALUES ('Hombre');
INSERT INTO GENDERS (NAME) VALUES ('Mujer');

-- Inserts para JOBS
INSERT INTO JOBS (NAME, SALARY) VALUES ('Gerente', 65355.30);
INSERT INTO JOBS (NAME, SALARY) VALUES ('Programador', 45900.90);
INSERT INTO JOBS (NAME, SALARY) VALUES ('Scrum Master', 55788.99);